# Default values for my_chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

labeling:
  label: "nginx-test"
  match_label: "nginx"

image:
  name: "my-nginx"
  repository: "nginx"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.24.0"

namespace : "default"

imagePullSecrets: []
nameOverride: "test"
fullnameOverride: "testing"

service:
  type: "NodePort"
  port: 80
  name: "nginx-service"

volume:
  name: "config-volume"
  configmap_name: "nginx-m1"
