apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.labeling.label }}
  labels:
    app: nginx
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.labeling.match_label }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      name: http
